// react/src/components/Main.js
import { Button, Container, Row, Col } from "react-bootstrap";
import { connect } from "react-redux";
import { increment, decrement, reset } from "../store/actions";

function Main (props) {
  const { count, increment, decrement, reset } = props;
  return (
    <Container>
          <Row className="my-2">
            <Col>Счётчик: {count}</Col>
          </Row>
          <Row>
            <Col>
              <Button className="me-2" variant="primary" onClick={increment}>+</Button>
              <Button className="me-2" variant="primary" onClick={decrement}>-</Button>
              <Button variant="danger" onClick={reset}>Сброс</Button>
            </Col>
          </Row>
        </Container>
  )
}

const mapStateToProps = (state) => ({
  count: state.count,
});

const mapDispatchToProps = (dispatch) => ({
  increment: () => dispatch(increment()),
  decrement: () => dispatch(decrement()),
  reset: () => dispatch(reset()),
});

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(Main);

// vuejs/src/components/Main.vue
<template>
  <div class="container">
    <div class="row my-2">
      <div class="col">Счётчик: {{ counter }}</div>
    </div>
    <div class="row">
      <div class="col">
        <button
          class="btn btn-primary me-2"
          type="button"
          @click="stateHandle('increment')"
        >
          +
        </button>
        <button
          class="btn btn-primary me-2"
          type="button"
          @click="stateHandle('decrement')"
        >
          -
        </button>
        <button
          class="btn btn-danger"
          type="button"
          @click="reset()"
        >
          сброс
        </button>
      </div>
    </div>
  </div>
</template>

<script>
import { computed } from "vue";
import { useStore } from "vuex";

export default {
  name: "Main",
  setup() {
    const store = useStore();
    return {
      counter: computed(() => store.getters.counter),
      stateHandle: function (type) {
        store.commit(type);
      },
      reset: function () {
        store.dispatch('reset');
      },
    };
  },
};
</script>

<style scoped>
</style>
